---  

- hosts: all

  tasks:

    - ansible.builtin.shell: crontab -l
      register: ansible_var
    - name: "get cron jobs"
      ansible.builtin.cron:
        name: "Curl"
        minute: "0"
    - ansible.builtin.debug:
        var: ansible_var
        when: ansible_var.stdout.find('Curl') == -1



    