---  

- hosts: all
  tasks:
    - name: get cron jobs
      ansible.builtin.cron:
        name: "Curl"
        minute: "0"
        hour: "1"
        job: "crontab -l"
      register: ansible_var
    - ansible.builtin.debug:
        var: ansible_var



    